spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888
      discovery:
        enabled: true  #是从配置中心读取文件
        service-id: config-server  #配置中心的servieId，即服务名

server:
  port: 8881

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
