
spring:
  application:
    name: eurka-server

server:
  port: 8762

eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.200.1:8761/eureka/,http://192.168.200.133:8762/eureka/
#  server:
#    enable-self-preservation: false #关闭自我保护，注册中心将不可用的实例删除
